apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockchain-explorer.fullname" . }}
  labels:
    {{- include "blockchain-explorer.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_PORT: {{ .Values.env.APP_PORT | quote }}
  REDIS_HOST: {{ include "blockchain-explorer.redisHost" . | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  METRICS_ENABLED: {{ .Values.env.METRICS_ENABLED | quote }}
  FEATURE_NEWS_ENABLED: {{ .Values.env.FEATURE_NEWS_ENABLED | quote }}
  FEATURE_PRICE_ALERTS_ENABLED: {{ .Values.env.FEATURE_PRICE_ALERTS_ENABLED | quote }}
  API_KEYS_ENABLED: {{ .Values.env.API_KEYS_ENABLED | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.RESPONSE_COMPRESSION_ENABLED | quote }}
  GETBLOCK_BASE_URL: {{ .Values.config.getblockBaseUrl | quote }}
  ADMIN_USERNAME: {{ .Values.config.adminUsername | quote }}
  APP_BASE_URL: {{ .Values.config.appBaseUrl | quote }}
